MODULE = wolfssl

NO_AUTO_SRC = 1

#-------------------------------------------------------------#
# Default SSL/TLS source files                                #
#-------------------------------------------------------------#
SRC :=  internal.c \
        wolfio.c \
        keys.c \
        ssl.c \
        tls.c
		
#-------------------------------------------------------------#
# Optional SSL/TLS source files                               #
#-------------------------------------------------------------#

# Add to src when using build option: HAVE_OCSP
SRC +=  ocsp.c

# Add to src when using build option: HAVE_CRL
SRC +=  crl.c

# Add to src when using build option: WOLFSSL_TLS13
SRC +=  tls13.c

include $(RIOTBASE)/Makefile.base
